export { default as InputText } from './Text.vue'
export { default as InputTag } from './Tag.vue'
export { default as InputNumber } from './Number.vue'
export { default as InputCheckbox } from './Checkbox.vue'
export { default as InputCheckboxAll } from './CheckboxAll.vue'
export { default as InputRadio } from './Radio.vue'
export { default as InputToggle } from './Toggle.vue'